# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.debug=false

# read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.1,1.22)
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.244
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.1.0,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale.
mod_id=originel
# The human-readable display name for the mod.
mod_name=Lycania : L'Originel
# The license of the mod.
mod_license=LGPL-3.0
# The mod version. See https://semver.org/
mod_version=0.4.0
# The group ID for the mod. Matches the base package used for the mod sources.
mod_group_id=fr.lycania.originel
# The authors of the mod.
mod_authors=Lycania
# The description of the mod.
mod_description=Il y a 900 ans, quatre enfants ont reveille deux artefacts endormis dans un temple oublie. Une nuit ecarlate a fait naitre la malediction des loups-garous et des vampires.\nCorvin, frappe en marge du rituel, n'est devenu ni l'un ni l'autre : immortel, hybride, presque impossible a tuer, il fut banni.\n900 ans plus tard, il revient pour voler la Pierre de Clair de Lune qui maintient le Voile protecteur.\nCe mod ajoute la faction de l'Originel au serveur Lycania.

## Dependencies

# Vampirism (TeamLapen) - https://github.com/TeamLapen/Vampirism - LGPL-3.0
vampirism_minecraft_version=1.21
vampirism_version=1.10.12
# Werewolves (TeamLapen) - https://github.com/TeamLapen/Werewolves - LGPL-3.0
werewolves_minecraft_version=1.21
werewolves_version=2.0.3.3
# Armourer's Workshop - https://github.com/Armourers-Workshop/Armourers-Workshop - CC-BY-NC-SA-3.0
armourers_workshop_version=3.4.0-beta.3+1.21.1-neoforge
